name: Weekly API docs build

on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:

jobs:
  build:
    uses: pmmp/ApiDocsBuildAction/.github/workflows/build-docs.yml@4d9c533afbbe36608c245cf22d5b100b8a95ed3b
    with:
      src-repo: pmmp/PocketMine-MP
      ref: major-next
      pm-version-major: 5
