name: Weekly API docs build

on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:

jobs:
  build:
    uses: pmmp/ApiDocsBuildAction/.github/workflows/build-docs.yml@59fa20560b59b565fe79fd055bc58a966dca5412
    with:
      src-repo: pmmp/PocketMine-MP
      ref: major-next
      pm-version-major: 5
